<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bo\Bo.csproj" />
    <ProjectReference Include="..\Dados\Dados.csproj" />
    <ProjectReference Include="..\Exceptions\Exceptions.csproj" />
    <ProjectReference Include="..\Interfaces\Interfaces.csproj" />
    <ProjectReference Include="..\Validacoes\Validacoes.csproj" />
  </ItemGroup>

</Project>
